name: Build HeadphoneAmp

on:
  push:
    branches:
      - '**'  # 匹配所有分支
    tags:
      - 'v*'  # 匹配所有版本标签

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
        
    - name: Build Project
      run: |
        mkdir -p build
        clang -framework Foundation -framework IOKit \
          HeadphoneAmp.m \
          HeadphoneAmpDaemon.m \
          -arch x86_64 \
          -o build/HeadphoneAmpDaemon
          
    - name: Create Package
      run: |
        mkdir -p package/usr/local/bin
        mkdir -p package/Library/LaunchDaemons
        cp build/HeadphoneAmpDaemon package/usr/local/bin/
        cp com.headphone.amp.plist package/Library/LaunchDaemons/
        cd package
        zip -r ../HeadphoneAmp.zip .
        
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: HeadphoneAmp-${{ github.sha }}
        path: HeadphoneAmp.zip
        
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: HeadphoneAmp.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 